name: imgai
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.10
  - pandas
  - numpy
  - openpyxl          # Excel reader/writer
  - xlsxwriter        # Excel writer for formatting
  - regex             # filename parsing / cleanup
  - scipy             # core scientific computing

  # Visualization
  - matplotlib
  - seaborn
  - plotly
  - streamlit

  # Image processing
  - opencv
  - scikit-image
  - PyWavelets        # wavelet decomposition
  - pillow

  # Parallelization & utilities
  - joblib
  - tqdm
  - pyyaml

  # GUI (optional)
  - tk

  # Dev / Notebook support
  - ipykernel
  - jupyter
  - pip

  # Pip-only packages
  - pip:
      - pycwa         # if you rely on this
      - gdown         # download files from Google Drive
